# -*- coding: utf-8 -*-
"""Regenerate the sibling Blender repository's palette module from these sources.

The two theme sets share one palette. This repository owns the palette tables
(roles.py, themes.py); the Blender repository carries a generated copy so it can
stand alone without importing anything from here. Run this after changing a
colour, or the two products drift apart.

The generated file bakes in the FINAL values -- the tables plus the readability
pass in build_themes.polish(), which converges roles that appear on several
backgrounds at once. Baking is deliberate: the Blender side then needs neither
the tables nor that pass, and its own readability check has nothing left to fix.

Usage:
    python extract_palettes.py [--out PATH]
Defaults to ../blender-anime-themes/anime_palettes.py
"""
import argparse
import io
import os
import pprint
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import roles as idea_roles          # noqa: E402
import themes as idea_themes        # noqa: E402
import build_themes as idea_build   # noqa: E402

# the roles the Blender generator maps onto its text editor attributes
SYNTAX_ROLES = ("keyword", "string", "number", "comment", "predefined",
                "escape", "operator", "doc_tag", "soft_keyword")

HEADER = '''# -*- coding: utf-8 -*-
"""Palette data shared with the IntelliJ IDEA schemes of the sibling project.

GENERATED by idea_themes/extract_palettes.py -- do not edit by hand.

It bakes in the values the IDEA side produces: its palette tables plus the
readability pass that converges roles appearing on several backgrounds at once.
Baking them keeps this repository standalone (it imports nothing from outside).
If a colour changes there, re-run that script and this file follows.
"""

import colorsys
import os

'''

# The functions the Blender side needs. Kept in step with build_themes.adjust and
# preview.hx / load_font; they are copied here (rather than imported) so the
# generated module has no dependency on this repository.
HELPERS = '''

# --------------------------------------------------------------- helpers ----
def _rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _lum(h):
    def lin(c):
        c = c / 255.0
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = _rgb(h)
    return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)


def contrast(c1, c2):
    a, b = _lum(c1), _lum(c2)
    return round((max(a, b) + 0.05) / (min(a, b) + 0.05), 2)


def _hls_hex(h, l, s):
    r, g, b = colorsys.hls_to_rgb(h, l, s)
    return "#{:02x}{:02x}{:02x}".format(
        max(0, min(255, round(r * 255))),
        max(0, min(255, round(g * 255))),
        max(0, min(255, round(b * 255))))


def adjust(fg, bg, target):
    """Nudge lightness only, until fg/bg meets the contrast target.

    The direction moves away from the background rather than assuming a light or
    dark theme, because several backgrounds here are mid-tone (gold, vermilion).
    """
    if not bg or contrast(fg, bg) >= target:
        return fg
    r, g, b = _rgb(fg)
    h, l, s = colorsys.rgb_to_hls(r / 255.0, g / 255.0, b / 255.0)
    brighter = _lum(fg) >= _lum(bg)
    lo, hi = (l, 1.0) if brighter else (0.0, l)
    for _ in range(48):
        mid = (lo + hi) / 2.0
        if contrast(_hls_hex(h, mid, s), bg) >= target:
            hi, lo = (mid, lo) if brighter else (hi, mid)
        else:
            lo, hi = (mid, hi) if brighter else (lo, mid)
    found = _hls_hex(h, hi if brighter else lo, s)
    if contrast(found, bg) < target:
        for cand in ("#ffffff", "#000000", _hls_hex(h, 1.0 if brighter else 0.0, s)):
            if contrast(cand, bg) >= target:
                return cand
    return found


# ------------------------------------------------------ preview rendering ----
FONT_DIR = "C:/Windows/Fonts"
FACES = {
    0: ("consola.ttf", "consolab.ttf"),
    1: ("consolab.ttf", "consolab.ttf"),
    2: ("consolai.ttf", "consolaz.ttf"),
    3: ("consolaz.ttf", "consolaz.ttf"),
}


def hx(v):
    """The preview's drawing layer wants a leading '#'; the tables store bare hex."""
    if not v:
        return None
    return v if v.startswith("#") else "#" + v


def rgb(v):
    h = hx(v).lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def load_font(font_type, size=15, bold=False):
    from PIL import ImageFont
    key = 1 if bold else font_type
    reg, _bold = FACES.get(key, FACES[0])
    try:
        return ImageFont.truetype(os.path.join(FONT_DIR, reg), size)
    except OSError:
        return ImageFont.load_default()
'''


def collect():
    palettes = {}
    for name in idea_themes.PALETTES:
        p = dict(idea_themes.PALETTES[name])
        idea_themes.fix_palette(name, p)
        palettes[name] = p
    syntax = {}
    for theme in idea_roles.THEMES:
        idea_build.polish(theme)
        r = theme["roles"]
        syntax[theme["name"]] = {k: r[k]["fg"] for k in SYNTAX_ROLES}
    return palettes, syntax


def render():
    palettes, syntax = collect()
    return (HEADER
            + "PALETTES = "
            + pprint.pformat(palettes, indent=4, width=96, sort_dicts=False)
            + "\n\nEDITOR_ROLES = "
            + pprint.pformat(syntax, indent=4, width=96, sort_dicts=False)
            + "\n" + HELPERS)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(
        os.path.dirname(HERE), "blender-anime-themes", "anime_palettes.py"))
    args = ap.parse_args()
    body = render()
    with io.open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    palettes, syntax = collect()
    print(f"wrote {args.out}")
    print(f"  {len(palettes)} palettes, {len(syntax)} role sets, {len(body)} bytes")
    print("  now re-run blender_themes.py in that repository")


if __name__ == "__main__":
    main()
