# -*- coding: utf-8 -*-
"""Role table for the four IntelliJ IDEA colour schemes.

Attribute and colour-option names here are taken from the schemes bundled with
IntelliJ IDEA 2025.2 (IC-252.28539.97) --
  lib/app-client.jar      themes/Light.xml, themes/expUI/expUI_darkScheme.xml
  plugins/markdown/...    colorSchemes/MarkdownDefault.xml, MarkdownDarcula.xml
  plugins/yaml/...        colorSchemes/YAMLDarcula.xml
  plugins/Groovy/...      colorSchemes/GroovyDefault.xml
  lib/app.jar             colorSchemes/XmlDarcula.xml
Anything not present in those files was dropped rather than guessed at, because
IDEA silently ignores option names it does not know.

Palettes were sampled from the two source images:
  Kurumi Tokisaki  C:/Users/kb/Pictures/时崎狂三.png
  Hatsune Miku     E:/下载/初音未来.jpeg
"""

PLAIN, BOLD, ITALIC, BOLD_ITALIC = 0, 1, 2, 3
E_LINE, E_WAVE, E_BOLD_LINE, E_STRIKE, E_DOTTED, E_DASHED = 0, 1, 2, 3, 4, 5


def R(fg=None, font=PLAIN, effect=None, eff_fg=None, bg=None):
    return dict(fg=fg, font=font, effect=effect, eff_fg=eff_fg, bg=bg)


# ==========================================================================
#  Kurumi Tokisaki Light -- warm white, gold keywords, vermilion strings
# ==========================================================================
KURUMI_LIGHT = dict(
    name="Kurumi Tokisaki Light",
    parent="Default",
    created="2026-09-17T10:00:00",
    roles={
        "text":           R("#2B2933", bg="#FBF9F7"),
        "keyword":        R("#8C6414", BOLD),
        "soft_keyword":   R("#8C6414"),
        "string":         R("#B03A22"),
        "escape":         R("#AC601C"),
        "invalid":        R("#E5112C", BOLD),
        "number":         R("#982850"),
        "constant":       R("#982850"),
        "label":          R("#982850"),
        "function":       R("#7A2E4A"),
        "reassigned":     R("#7A2E4A", ITALIC),
        "class_name":     R("#2B2933", BOLD),
        "type_parameter": R("#AC601C"),
        "field":          R("#4A4650"),
        "static_field":   R("#4A4650", ITALIC),
        "static_method":  R("#7A2E4A", ITALIC),
        "local":          R("#35323C"),
        "parameter":      R("#4A4650"),
        "operator":       R("#6A646C"),
        "annotation":     R("#AC601C"),
        "tag":            R("#8C6414"),
        "attribute":      R("#AC601C"),
        "attribute_value": R("#B03A22"),
        "predefined":     R("#7A2E4A"),
        "comment":        R("#767E89", ITALIC),
        "doc":            R("#817B87", ITALIC),
        "doc_markup":     R("#8C6414"),
        "doc_tag":        R("#8C6414", BOLD),
        "error":          R("#E5112C", BOLD, E_WAVE, "#E5112C"),
        "warning":        R("#A96200", PLAIN, E_WAVE, "#A96200"),
        "weak_warning":   R("#9E7553", PLAIN, E_DOTTED, "#9E7553"),
        "info":           R("#6C747E", PLAIN, E_DOTTED, "#6C747E"),
        # supporting roles
        "selection_bg":   R(bg="#F6D9D4"),
        "brace_bg":       R(bg="#F0DCD6"),
        "brace_bad_bg":   R(bg="#F7C9C4"),
        "search_bg":      R(bg="#F0C86A"),
        "search_fg":      R("#2B2933"),
        "search_write_bg": R(bg="#E8B84A"),
        "search_write_fg": R("#2B2933"),
        "caret_id_bg":    R(bg="#EFE6E0"),
        "caret_write_bg": R(bg="#F3DDD8"),
        "fold_bg":        R(bg="#F0EBE9"),
        "exec_bg":        R(bg="#E7E3DF"),
        "hint_bg":        R(bg="#EDE8E4"),
        "hint_fg":        R("#6C747E"),
        "inlay":          R("#6C747D"),
        "inlay_bg":       R(bg="#EDE8E4"),
        "todo":           R("#982850", BOLD),
        "link":           R("#7A2E4A"),
        "bookmark":       R("#7A2E4A"),
        "breakpoint_fg":  R("#FFFFFF", BOLD),
        "breakpoint_bg":  R(bg="#B03A22"),
    },
    colors={
        "CARET_ROW_COLOR": "F4F0EE",
        "CARET_COLOR": "2B2933",
        "SELECTION_BACKGROUND": "F6D9D4",
        "LINE_NUMBERS_COLOR": "A8A4AC",
        "LINE_NUMBER_ON_CARET_ROW_COLOR": "8C6414",
        "GUTTER_BACKGROUND": "FBF9F7",
        "INDENT_GUIDE": "E4DEDC",
        "SELECTED_INDENT_GUIDE": "C8C2C0",
        "VISUAL_INDENT_GUIDE": "E4DEDC",
        "WHITESPACES": "D8D2D0",
        "WHITESPACES_MODIFIED_LINES_COLOR": "D8D2D0",
        "ERROR_STRIPE_COLOR": "E5112C",
        "RIGHT_MARGIN_COLOR": "E4DEDC",
        "TEARLINE_COLOR": "E4DEDC",
        "FOLDED_TEXT_BORDER_COLOR": "D8D2D0",
        "METHOD_SEPARATORS_COLOR": "E4DEDC",
        "ADDED_LINES_COLOR": "E3EFDC",
        "DELETED_LINES_COLOR": "F8DCD8",
        "MODIFIED_LINES_COLOR": "F2E7D4",
        "IGNORED_ADDED_LINES_BORDER_COLOR": "E3EFDC",
        "IGNORED_DELETED_LINES_BORDER_COLOR": "F8DCD8",
        "IGNORED_MODIFIED_LINES_BORDER_COLOR": "F2E7D4",
        "DIFF_SEPARATORS_BACKGROUND": "E4DEDC",
        "CONSOLE_BACKGROUND_KEY": "FBF9F7",
        "CONSOLE_NORMAL_OUTPUT": "2B2933",
        "CONSOLE_ERROR_OUTPUT": "E5112C",
        "CONSOLE_USER_INPUT": "8C6414",
        "CONSOLE_SYSTEM_OUTPUT": "767E89",
        "CONSOLE_RANGE_TO_EXECUTE": "F6D9D4",
        "NOTIFICATION_BACKGROUND": "FBF9F7",
        "DOCUMENTATION_COLOR": "F7F3F0",
        "LOOKUP_COLOR": "F0C86A",
        "RECENT_LOCATIONS_SELECTION": "F6D9D4",
        "CODE_LENS_BORDER_COLOR": "E4DEDC",
        "BREADCRUMBS_DEFAULT": "767E89",
        "BREADCRUMBS_INACTIVE": "817B87",
        "BREADCRUMBS_HOVERED": "7A2E4A",
        "BREADCRUMBS_CURRENT": "2B2933",
    },
)

# ==========================================================================
#  Kurumi Tokisaki Dark -- charcoal, gold keywords, vermilion strings
# ==========================================================================
KURUMI_DARK = dict(
    name="Kurumi Tokisaki Dark",
    parent="Darcula",
    created="2026-09-17T10:00:00",
    roles={
        "text":           R("#D8D4DE", bg="#1E1C22"),
        "keyword":        R("#E0A838", BOLD),
        "soft_keyword":   R("#E0A838"),
        "string":         R("#E8604F"),
        "escape":         R("#F0A878"),
        "invalid":        R("#FF4D4D", BOLD),
        "number":         R("#E8C870"),
        "constant":       R("#E8C870"),
        "label":          R("#C76581"),
        "function":       R("#F0A878"),
        "reassigned":     R("#F0A878", ITALIC),
        "class_name":     R("#C2D8F2", BOLD),
        "type_parameter": R("#C76581"),
        "field":          R("#C8C4CE"),
        "static_field":   R("#C8C4CE", ITALIC),
        "static_method":  R("#F0A878", ITALIC),
        "local":          R("#C8C4CE"),
        "parameter":      R("#A8A4B2"),
        "operator":       R("#8E8A98"),
        "annotation":     R("#C76581"),
        "tag":            R("#E0A838"),
        "attribute":      R("#C2D8F2"),
        "attribute_value": R("#E8604F"),
        "predefined":     R("#F0A878"),
        "comment":        R("#8E959E", ITALIC),
        "doc":            R("#7C7887", ITALIC),
        "doc_markup":     R("#E0A838"),
        "doc_tag":        R("#E0A838", BOLD),
        "error":          R("#FF4D4D", BOLD, E_WAVE, "#FF4D4D"),
        "warning":        R("#D8D4DE", PLAIN, E_WAVE, "#D8A03C"),
        "weak_warning":   R("#8E8A98", PLAIN, E_DOTTED, "#8E7A3A"),
        "info":           R("#7AB8E8", PLAIN, E_DOTTED, "#7AB8E8"),
        "selection_bg":   R(bg="#4A2430"),
        "brace_bg":       R(bg="#3A3038"),
        "brace_bad_bg":   R(bg="#6B2A30"),
        "search_bg":      R(bg="#C9A227"),
        "search_fg":      R("#2A2530"),
        "search_write_bg": R(bg="#A88A22"),
        "search_write_fg": R("#2A2530"),
        "caret_id_bg":    R(bg="#332F3C"),
        "caret_write_bg": R(bg="#3E2A30"),
        "fold_bg":        R(bg="#282530"),
        "exec_bg":        R(bg="#26232E"),
        "hint_bg":        R(bg="#26232E"),
        "hint_fg":        R("#8E8A98"),
        "inlay":          R("#8E8A98"),
        "inlay_bg":       R(bg="#26232E"),
        "todo":           R("#C05070", BOLD),
        "link":           R("#7AB8E8"),
        "bookmark":       R("#C05070"),
        "breakpoint_fg":  R("#1E1C22", BOLD),
        "breakpoint_bg":  R(bg="#E8604F"),
    },
    colors={
        "CARET_ROW_COLOR": "282530",
        "CARET_COLOR": "D8D4DE",
        "SELECTION_BACKGROUND": "4A2430",
        "LINE_NUMBERS_COLOR": "5C5866",
        "LINE_NUMBER_ON_CARET_ROW_COLOR": "E0A838",
        "GUTTER_BACKGROUND": "1E1C22",
        "INDENT_GUIDE": "2E2B36",
        "SELECTED_INDENT_GUIDE": "3E3A48",
        "VISUAL_INDENT_GUIDE": "2E2B36",
        "WHITESPACES": "2A2830",
        "WHITESPACES_MODIFIED_LINES_COLOR": "2A2830",
        "ERROR_STRIPE_COLOR": "FF4D4D",
        "RIGHT_MARGIN_COLOR": "2E2B36",
        "TEARLINE_COLOR": "2E2B36",
        "FOLDED_TEXT_BORDER_COLOR": "3E3A48",
        "METHOD_SEPARATORS_COLOR": "2E2B36",
        "ADDED_LINES_COLOR": "243026",
        "DELETED_LINES_COLOR": "3A2028",
        "MODIFIED_LINES_COLOR": "32303E",
        "IGNORED_ADDED_LINES_BORDER_COLOR": "243026",
        "IGNORED_DELETED_LINES_BORDER_COLOR": "3A2028",
        "IGNORED_MODIFIED_LINES_BORDER_COLOR": "32303E",
        "DIFF_SEPARATORS_BACKGROUND": "2E2B36",
        "CONSOLE_BACKGROUND_KEY": "1E1C22",
        "CONSOLE_NORMAL_OUTPUT": "D8D4DE",
        "CONSOLE_ERROR_OUTPUT": "FF4D4D",
        "CONSOLE_USER_INPUT": "E0A838",
        "CONSOLE_SYSTEM_OUTPUT": "8E959E",
        "CONSOLE_RANGE_TO_EXECUTE": "4A2430",
        "NOTIFICATION_BACKGROUND": "1E1C22",
        "DOCUMENTATION_COLOR": "26232E",
        "LOOKUP_COLOR": "4A3A1E",
        "RECENT_LOCATIONS_SELECTION": "4A2430",
        "CODE_LENS_BORDER_COLOR": "2E2B36",
        "BREADCRUMBS_DEFAULT": "8E8A98",
        "BREADCRUMBS_INACTIVE": "7C7887",
        "BREADCRUMBS_HOVERED": "C2D8F2",
        "BREADCRUMBS_CURRENT": "D8D4DE",
    },
)

# ==========================================================================
#  Hatsune Miku Light -- warm pink-white, azure keywords, teal strings
# ==========================================================================
MIKU_LIGHT = dict(
    name="Hatsune Miku Light",
    parent="Default",
    created="2026-09-17T10:00:00",
    roles={
        "text":           R("#2A3B45", bg="#FBF7FA"),
        "keyword":        R("#0777BF", BOLD),
        "soft_keyword":   R("#0777BF"),
        "string":         R("#1D8169"),
        "escape":         R("#B2593B"),
        "invalid":        R("#D32F2F", BOLD),
        "number":         R("#B2593B"),
        "constant":       R("#B2593B"),
        "label":          R("#AD5776"),
        "function":       R("#005EA8"),
        "reassigned":     R("#005EA8", ITALIC),
        "class_name":     R("#0B3F63", BOLD),
        "type_parameter": R("#AD5776"),
        "field":          R("#4A6572"),
        "static_field":   R("#4A6572", ITALIC),
        "static_method":  R("#005EA8", ITALIC),
        "local":          R("#33505F"),
        "parameter":      R("#4A6572"),
        "operator":       R("#5C7681"),
        "annotation":     R("#AD5776"),
        "tag":            R("#0777BF"),
        "attribute":      R("#AD5776"),
        "attribute_value": R("#1D8169"),
        "predefined":     R("#005EA8"),
        "comment":        R("#618099", ITALIC),
        "doc":            R("#4F7A99", ITALIC),
        "doc_markup":     R("#0777BF"),
        "doc_tag":        R("#0777BF", BOLD),
        "error":          R("#D32F2F", BOLD, E_WAVE, "#D32F2F"),
        "warning":        R("#A76200", PLAIN, E_WAVE, "#A76200"),
        "weak_warning":   R("#94784F", PLAIN, E_DOTTED, "#94784F"),
        "info":           R("#0777BF", PLAIN, E_DOTTED, "#0777BF"),
        "selection_bg":   R(bg="#D6EBFA"),
        "brace_bg":       R(bg="#DCEAF4"),
        "brace_bad_bg":   R(bg="#F6CFD8"),
        "search_bg":      R(bg="#F7D9E4"),
        "search_fg":      R("#2A3B45"),
        "search_write_bg": R(bg="#F3CFDD"),
        "search_write_fg": R("#2A3B45"),
        "caret_id_bg":    R(bg="#E4F0F8"),
        "caret_write_bg": R(bg="#DFECF5"),
        "fold_bg":        R(bg="#F0EDF4"),
        "exec_bg":        R(bg="#EAE6F0"),
        "hint_bg":        R(bg="#EBF2F7"),
        "hint_fg":        R("#5C7681"),
        "inlay":          R("#7FA0B8"),
        "inlay_bg":       R(bg="#EBF2F7"),
        "todo":           R("#B05C7A", BOLD),
        "link":           R("#0070C0"),
        "bookmark":       R("#B05C7A"),
        "breakpoint_fg":  R("#FFFFFF", BOLD),
        "breakpoint_bg":  R(bg="#D32F2F"),
    },
    colors={
        "CARET_ROW_COLOR": "F2EDF5",
        "CARET_COLOR": "2A3B45",
        "SELECTION_BACKGROUND": "D6EBFA",
        "LINE_NUMBERS_COLOR": "9AB0BE",
        "LINE_NUMBER_ON_CARET_ROW_COLOR": "0777BF",
        "GUTTER_BACKGROUND": "FBF7FA",
        "INDENT_GUIDE": "E2E8EE",
        "SELECTED_INDENT_GUIDE": "C4D2DC",
        "VISUAL_INDENT_GUIDE": "E2E8EE",
        "WHITESPACES": "DCE4EA",
        "WHITESPACES_MODIFIED_LINES_COLOR": "DCE4EA",
        "ERROR_STRIPE_COLOR": "D32F2F",
        "RIGHT_MARGIN_COLOR": "E2E8EE",
        "TEARLINE_COLOR": "E2E8EE",
        "FOLDED_TEXT_BORDER_COLOR": "C4D2DC",
        "METHOD_SEPARATORS_COLOR": "E2E8EE",
        "ADDED_LINES_COLOR": "E3EFDC",
        "DELETED_LINES_COLOR": "F8E0E6",
        "MODIFIED_LINES_COLOR": "E8EEF6",
        "IGNORED_ADDED_LINES_BORDER_COLOR": "E3EFDC",
        "IGNORED_DELETED_LINES_BORDER_COLOR": "F8E0E6",
        "IGNORED_MODIFIED_LINES_BORDER_COLOR": "E8EEF6",
        "DIFF_SEPARATORS_BACKGROUND": "E2E8EE",
        "CONSOLE_BACKGROUND_KEY": "FBF7FA",
        "CONSOLE_NORMAL_OUTPUT": "2A3B45",
        "CONSOLE_ERROR_OUTPUT": "D32F2F",
        "CONSOLE_USER_INPUT": "0777BF",
        "CONSOLE_SYSTEM_OUTPUT": "618099",
        "CONSOLE_RANGE_TO_EXECUTE": "D6EBFA",
        "NOTIFICATION_BACKGROUND": "FBF7FA",
        "DOCUMENTATION_COLOR": "F2EFF5",
        "LOOKUP_COLOR": "F7D9E4",
        "RECENT_LOCATIONS_SELECTION": "D6EBFA",
        "CODE_LENS_BORDER_COLOR": "E2E8EE",
        "BREADCRUMBS_DEFAULT": "618099",
        "BREADCRUMBS_INACTIVE": "7F97A8",
        "BREADCRUMBS_HOVERED": "005EA8",
        "BREADCRUMBS_CURRENT": "2A3B45",
    },
)

# ==========================================================================
#  Hatsune Miku Dark -- deep sea blue (derived; the source image has no darks)
# ==========================================================================
MIKU_DARK = dict(
    name="Hatsune Miku Dark",
    parent="Darcula",
    created="2026-09-17T10:00:00",
    roles={
        "text":           R("#C0D6E4", bg="#0B1A2A"),
        "keyword":        R("#48C0F8", BOLD),
        "soft_keyword":   R("#48C0F8"),
        "string":         R("#F0B8CC"),
        "escape":         R("#A8E8F0"),
        "invalid":        R("#FF5F56", BOLD),
        "number":         R("#A8E8F0"),
        "constant":       R("#A8E8F0"),
        "label":          R("#C8B0E8"),
        "function":       R("#5FD0C0"),
        "reassigned":     R("#5FD0C0", ITALIC),
        "class_name":     R("#C7E1F9", BOLD),
        "type_parameter": R("#C8B0E8"),
        "field":          R("#9EBDD0"),
        "static_field":   R("#9EBDD0", ITALIC),
        "static_method":  R("#5FD0C0", ITALIC),
        "local":          R("#9EBDD0"),
        "parameter":      R("#7FA0B8"),
        "operator":       R("#6E90A8"),
        "annotation":     R("#C8B0E8"),
        "tag":            R("#48C0F8"),
        "attribute":      R("#C8B0E8"),
        "attribute_value": R("#F0B8CC"),
        "predefined":     R("#5FD0C0"),
        "comment":        R("#5A7B95", ITALIC),
        "doc":            R("#6B93B0", ITALIC),
        "doc_markup":     R("#48C0F8"),
        "doc_tag":        R("#48C0F8", BOLD),
        "error":          R("#FF5F56", BOLD, E_WAVE, "#FF5F56"),
        "warning":        R("#E8B84A", PLAIN, E_WAVE, "#E8B84A"),
        "weak_warning":   R("#A08050", PLAIN, E_DOTTED, "#A08050"),
        "info":           R("#48C0F8", PLAIN, E_DOTTED, "#48C0F8"),
        "selection_bg":   R(bg="#1B4A6E"),
        "brace_bg":       R(bg="#1A3D52"),
        "brace_bad_bg":   R(bg="#5E2A36"),
        "search_bg":      R(bg="#3A9BD8"),
        "search_fg":      R("#0B1A2A"),
        "search_write_bg": R(bg="#2E7FB8"),
        "search_write_fg": R("#0B1A2A"),
        "caret_id_bg":    R(bg="#183448"),
        "caret_write_bg": R(bg="#1E4258"),
        "fold_bg":        R(bg="#12283C"),
        "exec_bg":        R(bg="#14293C"),
        "hint_bg":        R(bg="#14293C"),
        "hint_fg":        R("#7FA0B8"),
        "inlay":          R("#5A7A94"),
        "inlay_bg":       R(bg="#14293C"),
        "todo":           R("#F0B8CC", BOLD),
        "link":           R("#48C0F8"),
        "bookmark":       R("#C8B0E8"),
        "breakpoint_fg":  R("#0B1A2A", BOLD),
        "breakpoint_bg":  R(bg="#FF5F56"),
    },
    colors={
        "CARET_ROW_COLOR": "12283C",
        "CARET_COLOR": "C0D6E4",
        "SELECTION_BACKGROUND": "1B4A6E",
        "LINE_NUMBERS_COLOR": "4A6478",
        "LINE_NUMBER_ON_CARET_ROW_COLOR": "48C0F8",
        "GUTTER_BACKGROUND": "0B1A2A",
        "INDENT_GUIDE": "16303F",
        "SELECTED_INDENT_GUIDE": "22506A",
        "VISUAL_INDENT_GUIDE": "16303F",
        "WHITESPACES": "152C3A",
        "WHITESPACES_MODIFIED_LINES_COLOR": "152C3A",
        "ERROR_STRIPE_COLOR": "FF5F56",
        "RIGHT_MARGIN_COLOR": "16303F",
        "TEARLINE_COLOR": "16303F",
        "FOLDED_TEXT_BORDER_COLOR": "22506A",
        "METHOD_SEPARATORS_COLOR": "16303F",
        "ADDED_LINES_COLOR": "14303A",
        "DELETED_LINES_COLOR": "38222C",
        "MODIFIED_LINES_COLOR": "1B3A4E",
        "IGNORED_ADDED_LINES_BORDER_COLOR": "14303A",
        "IGNORED_DELETED_LINES_BORDER_COLOR": "38222C",
        "IGNORED_MODIFIED_LINES_BORDER_COLOR": "1B3A4E",
        "DIFF_SEPARATORS_BACKGROUND": "16303F",
        "CONSOLE_BACKGROUND_KEY": "0B1A2A",
        "CONSOLE_NORMAL_OUTPUT": "C0D6E4",
        "CONSOLE_ERROR_OUTPUT": "FF5F56",
        "CONSOLE_USER_INPUT": "48C0F8",
        "CONSOLE_SYSTEM_OUTPUT": "5A7B95",
        "CONSOLE_RANGE_TO_EXECUTE": "1B4A6E",
        "NOTIFICATION_BACKGROUND": "0B1A2A",
        "DOCUMENTATION_COLOR": "12283C",
        "LOOKUP_COLOR": "1B4A6E",
        "RECENT_LOCATIONS_SELECTION": "1B4A6E",
        "CODE_LENS_BORDER_COLOR": "16303F",
        "BREADCRUMBS_DEFAULT": "5A7B95",
        "BREADCRUMBS_INACTIVE": "456075",
        "BREADCRUMBS_HOVERED": "C7E1F9",
        "BREADCRUMBS_CURRENT": "C0D6E4",
    },
)

THEMES = [KURUMI_LIGHT, KURUMI_DARK, MIKU_LIGHT, MIKU_DARK]

# ==========================================================================
#  language token attributes -- (option name, role)
# ==========================================================================
ATTR_MAP = [
    ("DEFAULT_IDENTIFIER", "text"),
    ("DEFAULT_KEYWORD", "keyword"),
    ("DEFAULT_STRING", "string"),
    ("DEFAULT_NUMBER", "number"),
    ("DEFAULT_LINE_COMMENT", "comment"),
    ("DEFAULT_BLOCK_COMMENT", "comment"),
    ("DEFAULT_DOC_COMMENT", "doc"),
    ("DEFAULT_DOC_MARKUP", "doc_markup"),
    ("DEFAULT_DOC_COMMENT_TAG", "doc_tag"),
    ("DEFAULT_DOC_COMMENT_TAG_VALUE", "escape"),
    ("DEFAULT_OPERATION_SIGN", "operator"),
    ("DEFAULT_BRACES", "operator"),
    ("DEFAULT_BRACKETS", "operator"),
    ("DEFAULT_PARENTHS", "operator"),
    ("DEFAULT_DOT", "operator"),
    ("DEFAULT_COMMA", "operator"),
    ("DEFAULT_SEMICOLON", "operator"),
    ("DEFAULT_LABEL", "label"),
    ("DEFAULT_CONSTANT", "constant"),
    ("DEFAULT_CLASS_REFERENCE", "class_name"),
    ("DEFAULT_HIGHLIGHTED_REFERENCE", "class_name"),
    ("DEFAULT_INSTANCE_METHOD", "function"),
    ("DEFAULT_INSTANCE_FIELD", "field"),
    ("DEFAULT_STATIC_FIELD", "static_field"),
    ("DEFAULT_STATIC_METHOD", "static_method"),
    ("DEFAULT_FUNCTION_DECLARATION", "function"),
    ("DEFAULT_FUNCTION_CALL", "function"),
    ("DEFAULT_METADATA", "annotation"),
    ("DEFAULT_VALID_STRING_ESCAPE", "escape"),
    ("DEFAULT_INVALID_STRING_ESCAPE", "invalid"),
    ("DEFAULT_TAG", "tag"),
    ("DEFAULT_ATTRIBUTE", "attribute"),
    ("DEFAULT_REASSIGNED_LOCAL_VARIABLE", "reassigned"),
    ("DEFAULT_REASSIGNED_PARAMETER", "reassigned"),
    ("DEFAULT_ENTITY", "constant"),
    ("TYPE_PARAMETER_NAME_ATTRIBUTES", "type_parameter"),
    ("INSTANCE_FIELD_ATTRIBUTES", "field"),
    ("STATIC_FIELD_ATTRIBUTES", "static_field"),
    ("STATIC_FINAL_FIELD_ATTRIBUTES", "constant"),
    ("STATIC_METHOD_ATTRIBUTES", "static_method"),
    ("ANNOTATION_NAME_ATTRIBUTES", "annotation"),
    ("ANNOTATION_ATTRIBUTE_NAME_ATTRIBUTES", "attribute"),
    ("IMPLICIT_ANONYMOUS_CLASS_PARAMETER_ATTRIBUTES", "parameter"),
    ("NOT_USED_ELEMENT_ATTRIBUTES", "comment"),
]

# language families that mirror the DEFAULT_* spellings under a prefix
_PREFIX_MAP = [
    ("IDENTIFIER", "text"), ("KEYWORD", "keyword"), ("SOFT_KEYWORD", "soft_keyword"),
    ("STRING", "string"), ("NUMBER", "number"), ("CONSTANT", "constant"),
    ("LINE_COMMENT", "comment"), ("BLOCK_COMMENT", "comment"),
    ("DOC_COMMENT", "doc"), ("DOC_MARKUP", "doc_markup"), ("DOC_TAG", "doc_tag"),
    ("OPERATION_SIGN", "operator"), ("BRACES", "operator"),
    ("BRACKETS", "operator"), ("PARENTHS", "operator"), ("DOT", "operator"),
    ("COMMA", "operator"), ("SEMICOLON", "operator"), ("LABEL", "label"),
    ("CLASS_NAME", "class_name"), ("CLASS_REFERENCE", "class_name"),
    ("INTERFACE_NAME", "class_name"), ("ENUM_NAME", "class_name"),
    ("ANNOTATION_NAME", "annotation"), ("ANNOTATION", "annotation"),
    ("FUNCTION_DECLARATION", "function"), ("FUNCTION_CALL", "function"),
    ("METHOD_DECLARATION", "function"), ("METHOD_CALL", "function"),
    ("INSTANCE_METHOD", "function"),
    ("PARAMETER", "parameter"), ("LOCAL_VARIABLE", "local"),
    ("INSTANCE_FIELD", "field"), ("STATIC_FIELD", "static_field"),
    ("STATIC_METHOD", "static_method"),
    ("TYPE_PARAMETER", "type_parameter"),
    ("VALID_STRING_ESCAPE", "escape"), ("INVALID_STRING_ESCAPE", "invalid"),
    ("REASSIGNED_LOCAL_VARIABLE", "reassigned"),
    ("REASSIGNED_PARAMETER", "reassigned"),
    ("PROPERTY", "field"), ("MUTABLE_VARIABLE", "reassigned"),
    ("PACKAGE", "text"), ("TYPE_ALIAS", "class_name"), ("SELF", "keyword"),
]
for _prefix in ("JAVA_", "KOTLIN_", "GROOVY_"):
    for _suffix, _role in _PREFIX_MAP:
        ATTR_MAP.append((_prefix + _suffix, _role))

# names verified present in the 2025.2 bundles
ATTR_MAP += [
    ("KOTLIN_NAMED_ARGUMENT", "annotation"),
    ("KOTLIN_SMART_CAST_VALUE", "local"),
    ("KOTLIN_SMART_CAST_RECEIVER", "local"),
    ("KOTLIN_SMART_CONSTANT", "constant"),
    ("JS.GLOBAL_VARIABLE", "field"),
    ("JS.GLOBAL_FUNCTION", "function"),
    ("JS.LOCAL_VARIABLE", "local"),
    ("JS.INSTANCE_MEMBER_FUNCTION", "function"),
    ("JS.INSTANCE_MEMBER_VARIABLE", "field"),
    ("JS.STATIC_MEMBER_VARIABLE", "static_field"),
    ("JS.REGEXP", "string"),
    ("JS.KEYWORD", "keyword"),
    ("JS.STRING", "string"),
    ("JS.NUMBER", "number"),
    ("JS.LINE_COMMENT", "comment"),
    ("JS.BLOCK_COMMENT", "comment"),
    ("JS.DOC_COMMENT", "doc"),
    ("XML_TAG", "tag"),
    ("XML_TAG_NAME", "tag"),
    ("XML_CUSTOM_TAG_NAME", "tag"),
    ("XML_ATTRIBUTE_NAME", "attribute"),
    ("XML_ATTRIBUTE_VALUE", "attribute_value"),
    ("XML_ENTITY_REFERENCE", "constant"),
    ("XML_PROLOGUE", "doc"),
    ("HTML_TAG", "tag"),
    ("HTML_TAG_NAME", "tag"),
    ("HTML_CUSTOM_TAG_NAME", "tag"),
    ("HTML_ATTRIBUTE_NAME", "attribute"),
    ("HTML_ATTRIBUTE_VALUE", "attribute_value"),
    ("HTML_ENTITY_REFERENCE", "constant"),
    ("YAML_ANCHOR", "annotation"),
    ("YAML_ALIAS", "annotation"),
    ("YAML_KEY", "tag"),
    ("YAML_SCALAR_KEY", "tag"),
    ("YAML_SCALAR_VALUE", "string"),
    ("PROPERTIES.KEY", "tag"),
    ("PROPERTIES.VALUE", "string"),
    ("PROPERTIES.INVALID_STRING_ESCAPE", "invalid"),
    ("GHERKIN_PYSTRING", "string"),
    ("GHERKIN_REGEXP_PARAMETER", "escape"),
]

# Markdown -- names as defined in plugins/markdown MarkdownDefault.xml
ATTR_MAP += [
    ("MARKDOWN_TEXT", "text"),
    ("MARKDOWN_BOLD", "text"),
    ("MARKDOWN_ITALIC", "comment"),
    ("MARKDOWN_HEADER", "class_name"),
    ("MARKDOWN_HEADER_BOLD", "class_name"),
    ("MARKDOWN_CODE_SPAN", "string"),
    ("MARKDOWN_CODE_FENCE", "string"),
    ("MARKDOWN_LINK_TEXT", "function"),
    ("MARKDOWN_LINK_URL", "number"),
    ("MARKDOWN_AUTO_LINK", "number"),
    ("MARKDOWN_REFERENCE_LINK", "function"),
    ("MARKDOWN_IMAGE", "annotation"),
    ("MARKDOWN_BLOCKQUOTE", "comment"),
    ("MARKDOWN_LIST_BULLET", "keyword"),
]

# ==========================================================================
#  editor/IDE attributes -- (name, fg role, bg role, font, effect, effect role)
# ==========================================================================
ATTRS = [
    ("MATCHED_BRACE_ATTRIBUTES", None, "brace_bg", PLAIN, None, None),
    ("UNMATCHED_BRACE_ATTRIBUTES", None, "brace_bad_bg", PLAIN, None, None),
    ("MATCHED_TAG_NAME", None, "brace_bg", PLAIN, None, None),
    ("INLAY_DEFAULT", "inlay", "inlay_bg", PLAIN, None, None),
    ("INLINE_PARAMETER_HINT", "hint_fg", "hint_bg", PLAIN, None, None),
    ("INLINE_PARAMETER_HINT_CURRENT", "hint_fg", "selection_bg", PLAIN, None, None),
    ("INLINE_PARAMETER_HINT_HIGHLIGHTED", "hint_fg", "brace_bg", PLAIN, None, None),
    ("SEARCH_RESULT_ATTRIBUTES", "search_fg", "search_bg", PLAIN, None, None),
    ("WRITE_SEARCH_RESULT_ATTRIBUTES", "search_write_fg", "search_write_bg",
     PLAIN, None, None),
    ("IDENTIFIER_UNDER_CARET_ATTRIBUTES", None, "caret_id_bg", PLAIN, None, None),
    ("WRITE_IDENTIFIER_UNDER_CARET_ATTRIBUTES", None, "caret_write_bg", PLAIN, None, None),
    ("TODO_DEFAULT_ATTRIBUTES", "todo", None, PLAIN, None, None),
    ("HYPERLINK_ATTRIBUTES", "link", None, PLAIN, E_LINE, "link"),
    ("FOLLOWED_HYPERLINK_ATTRIBUTES", "comment", None, PLAIN, None, None),
    ("INACTIVE_HYPERLINK_ATTRIBUTES", "comment", None, PLAIN, E_LINE, "comment"),
    ("CTRL_CLICKABLE", "link", None, PLAIN, E_LINE, "link"),
    ("FOLDED_TEXT_ATTRIBUTES", "comment", "fold_bg", PLAIN, None, None),
    ("LIVE_TEMPLATE_ATTRIBUTES", None, "selection_bg", PLAIN, None, None),
    ("LIVE_TEMPLATE_INACTIVE_SEGMENT", "comment", None, PLAIN, None, None),
    ("TEMPLATE_VARIABLE_ATTRIBUTES", None, "caret_id_bg", PLAIN, None, None),
    ("BOOKMARKS_ATTRIBUTES", "bookmark", None, PLAIN, None, None),
    ("BREAKPOINT_ATTRIBUTES", "breakpoint_fg", "breakpoint_bg", PLAIN, None, None),
    ("EXECUTIONPOINT_ATTRIBUTES", None, "exec_bg", PLAIN, None, None),
    ("ERRORS_ATTRIBUTES", "error", None, PLAIN, E_WAVE, "error"),
    ("WARNING_ATTRIBUTES", "warning", None, PLAIN, E_WAVE, "warning"),
    ("WEAK_WARNING_ATTRIBUTES", "weak_warning", None, PLAIN, E_DOTTED, "weak_warning"),
    ("INFO_ATTRIBUTES", "info", None, PLAIN, E_DOTTED, "info"),
    ("GENERIC_SERVER_ERROR_OR_WARNING", "error", None, PLAIN, E_WAVE, "error"),
    ("DEPRECATED_ATTRIBUTES", "comment", None, PLAIN, E_STRIKE, "comment"),
    ("WRONG_REFERENCES_ATTRIBUTES", "error", None, PLAIN, E_WAVE, "error"),
    ("BAD_CHARACTER", "invalid", None, PLAIN, E_WAVE, "invalid"),
    ("TYPO", "weak_warning", None, PLAIN, E_WAVE, "weak_warning"),
    ("RUNTIME_ERROR", "error", None, PLAIN, E_WAVE, "error"),
    ("NOT_TOP_FRAME_ATTRIBUTES", "comment", None, PLAIN, None, None),
    ("TEXT_STYLE_ERROR", "error", None, PLAIN, None, None),
    ("TEXT_STYLE_WARNING", "warning", None, PLAIN, None, None),
    ("ERROR_HINT", None, "hint_bg", PLAIN, None, None),
    ("INFORMATION_HINT", None, "hint_bg", PLAIN, None, None),
    ("QUESTION_HINT", None, "hint_bg", PLAIN, None, None),
    ("INJECTED_LANGUAGE_FRAGMENT", None, "fold_bg", PLAIN, None, None),
    ("DOC_CODE_INLINE", "string", None, PLAIN, None, None),
    ("DOC_CODE_BLOCK", "string", None, PLAIN, None, None),
    ("DOC_COMMENT_LINK", "function", None, PLAIN, E_LINE, "function"),
    ("DOC_COMMENT_GUIDE", "operator", None, PLAIN, None, None),
    ("LOG_ERROR_OUTPUT", "error", None, PLAIN, None, None),
    ("LOG_WARNING_OUTPUT", "warning", None, PLAIN, None, None),
    ("LOG_INFO_OUTPUT", "info", None, PLAIN, None, None),
    ("LOG_VERBOSE_OUTPUT", "comment", None, PLAIN, None, None),
    ("DEBUGGER_INLINED_VALUES_MODIFIED", "number", None, PLAIN, None, None),
    ("DEBUGGER_INLINED_VALUES_EXECUTION_LINE", "number", None, PLAIN, None, None),
]

# ==========================================================================
#  readability floors -- WCAG contrast a foreground must reach
# ==========================================================================
TARGETS = {"comment": 3.9, "doc": 3.9, "deprecated": 3.9, "weak_warning": 3.9,
           "inlay": 3.9, "hint_fg": 3.9, "search_fg": 4.5, "search_write_fg": 4.5}
DEFAULT_TARGET = 4.5

# these are never drawn on the editor background, so measuring them against it
# would send the readability pass in the wrong direction
CONTEXTUAL = {"breakpoint_fg", "hint_fg", "inlay", "search_fg", "search_write_fg"}

# plain <colors> entries that hold a foreground, and what they sit on
FG_ENTRIES = {
    "BREADCRUMBS_DEFAULT": ("editor", 3.9),
    "BREADCRUMBS_INACTIVE": ("editor", 3.9),
    "BREADCRUMBS_HOVERED": ("editor", 4.5),
    "BREADCRUMBS_CURRENT": ("editor", 4.5),
    "LINE_NUMBERS_COLOR": ("GUTTER_BACKGROUND", 3.2),
    "LINE_NUMBER_ON_CARET_ROW_COLOR": ("GUTTER_BACKGROUND", 4.5),
    "CONSOLE_NORMAL_OUTPUT": ("CONSOLE_BACKGROUND_KEY", 4.5),
    "CONSOLE_ERROR_OUTPUT": ("CONSOLE_BACKGROUND_KEY", 4.5),
    "CONSOLE_USER_INPUT": ("CONSOLE_BACKGROUND_KEY", 4.5),
    "CONSOLE_SYSTEM_OUTPUT": ("CONSOLE_BACKGROUND_KEY", 3.9),
}

FILES = {
    "Kurumi Tokisaki Light": "KurumiTokisaki_Light.icls",
    "Kurumi Tokisaki Dark": "KurumiTokisaki_Dark.icls",
    "Hatsune Miku Light": "HatsuneMiku_Light.icls",
    "Hatsune Miku Dark": "HatsuneMiku_Dark.icls",
}
